FROM fluent/fluentd:v0.12.39

RUN apk add --update --virtual .build-deps sudo build-base ruby-dev \
  && sudo gem install fluent-plugin-elasticsearch \
  && sudo gem sources --clear-all \
  && apk del .build-deps \
  && rm -rf /var/cache/apk/* /home/fluentd/.gem/ruby/2.3.0/cache/*.gem


